FROM yangjiandong/base
MAINTAINER yangjiandong <59338947@qq.com>

RUN apt-get install -y \
    python-pip \
    libxml2-dev \
    libc6-dev \
    python2.7-dev \
    libpcre3 \
    libpcre3-dev \
    libgeoip1 \
    libgeoip-dev \
    libxslt1-dev \
    libjpeg62 \
    libjpeg62-dev \
    zlib1g-dev  \
    libfreetype6 \
    libfreetype6-dev \
    libmysqlclient-dev

#EOP
