version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=123
      - SUDO_PASSWORD=123
    volumes:
      - ./data/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
