version: "2.0"

networks:
  sonar_net:

services:
  pg_db:
    container_name: sonar_pg
    image: "postgres:14-alpine"
    restart: always
    networks:
      - sonar_net
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pdata
    ports:
      - "5432:5432"
    volumes:
      - ./pg/data:/var/lib/postgresql/data/
      - ./pg/init.db:/docker-entrypoint-initdb.d

  pgweb:
    container_name: sonar_pgweb
    restart: always
    image: sosedoff/pgweb
    networks:
      - sonar_net
    ports:
      - "8081:8081"
    links:
      - pg_db:pg_db
    environment:
      - DATABASE_URL=postgres://root:123@pg_db:5432/pdata?sslmode=disable
    depends_on:
      - pg_db

  sonar:
    image: sonarqube:9.2.4-community
    hostname: sonar
    container_name: sonar
    networks:
      - sonar_net
    env_file:
      - ./environment.env
    environment:
      SONARQUBE_JDBC_USERNAME: root
      SONARQUBE_JDBC_PASSWORD: 123
      SONARQUBE_JDBC_URL: jdbc:postgresql://pg_db:5432/pdata
      ES_JAVA_OPTS: -Xms1g -Xmx1g
    depends_on:
      - pg_db
    links:
      - pg_db:pg_db
    volumes:
      - ./sonar/extensions:/opt/sonarqube/extensions
      - ./sonar/logs:/opt/sonarqube/logs
      - ./sonar/data:/opt/sonarqube/data
      - ./sonar/conf:/opt/sonarqube/conf
    privileged: true
    ports:
      - 9000:9000
