global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10m
scrape_configs:
  - job_name: spring-boot
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /prometheus
    scheme: http
    static_configs:
      - targets:
        - 192.168.1.109:9001  #此处填写 Spring Boot 应用的 IP + 端口号