FROM million12/centos-supervisor:4.0.2

COPY locale.conf /etc/locale.conf
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN.UTF-8
ENV LC_ALL zh_CN.UTF-8
# locale -a 问题，不显示 zh_CN
RUN localedef -c -f UTF-8 -i zh_CN zh_CN.utf8
# RUN cp -f /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

# 注意，只能有一个 cmd，并且 docker run 指定cmd 时也会覆盖原有cmd
# /tmp/supervisord.log
CMD /usr/bin/supervisord -c /etc/supervisor/supervisord.conf

