# Docker Compose file for ELK stack

# Build with:
# docker-compose build elk

# Run with:
# docker-compose up

elk:
  #image: elkdocker_elk
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
    - "5000:5000"

  #  volumes:
  #  - ./elt_data:/var/lib/elasticsearch 
