version: "3"
services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
    - "./:/work/"
    ports:
    - "8888:8888"
    depends_on:
    - mysql
    tty: true
    privileged: true
    command: /bin/bash

  mysql:
    image: one/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      MSQL_ROOT_PASSWORD: "123"
      MSQL_USER: "root"
      MSQL_DATABASE: "u_data_db"
    # To persist data on the container:
    ports:
    - "3306:3306"
    # Where the data will be persisted:
    privileged: true
    volumes:
    - "./u_data/data/:/var/lib/mysql/"

