version: "2.1"

networks:
  sshapp-scloud:

services:
  mysql:
    container_name: mysql
    image: one/mysql:5.7
    hostname: mysql
    networks:
      - sshapp-scloud
    env_file:
      - ./environment.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql/mysql:/var/lib/mysql
      - ./mysql/mysql-conf:/etc/mysql
    privileged: true
    ports:
      - "${MYSQL_PORT}:3306"

  # nacos:
  #   container_name: nacos
  #   image: one/java:8
  #   hostname: nacos
  #   sysctls:
  #     net.ipv4.ip_local_port_range: "1024 65000"
  #   networks:
  #     - sshapp-scloud
  #   env_file:
  #     - ./environment.env
  #   volumes:
  #     - ./1.1.3:/workspace:rw
  #   privileged: true
  #   ports:
  #     - "${NACOS_PORT}:8848"
  #   working_dir: /workspace
  #   command: java -server -Xms128m -Xmx512m -jar  -Dnacos.standalone=true nacos-server.jar
  #   depends_on:
  #       - mysql
