hive:
  image: yangjiandong/hive:1.2.1
  volumes:
    - ./hive:/hive
    - ./:/work
  links:
    - mysql:mysql
  env_file: .env
  
mysql:
  image: yangjiandong/mysql:5.5
  volumes:
    - ./db:/var/lib/mysql
  environment:
    - DB_NAME=hive
  ports:
    - "3306:3306"

