version: "2"
services:
  nacos:
    image: one/nacos:0.9
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=mysql-master
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=123
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
    depends_on:
      - mysql-master
  mysql-master:
    container_name: mysql-master
    image: one/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-conf:/etc/mysql
    ports:
      - "3306:3306"
