version: "2"

services:
  postgres:
    container_name: sonar_pg
    image: "postgres:14-alpine"
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "max_connections=500"
      - "-c"
      - "shared_buffers=256MB"
    environment:
      POSTGRES_DB: pdata
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - ./pg/data:/var/lib/postgresql/data/
      - ./pg/init.db:/docker-entrypoint-initdb.d
      - ./pg/localtime:/etc/localtime
