version: '2'

services:

  app:
    image: nextcloud
    container_name: nextcloud
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html:rw
    restart: always
    privileged: true
    ports:
      - "8200:80"

  db:
    image: one/mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql/mysql:/var/lib/mysql:rw
      - ./mysql/conf:/etc/mysql:ro
    restart: always
    privileged: true
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

