web:
  build: .
  ports:
    - "8000:8000"
  volumes:
    - ./mysite:/code
  links:
    - mysql:mysql
    - redis:redis
  env_file: .env
#  command: /code/manage.py runserver 0.0.0.0:8000

mysql:
  #image: daocloud.io/mysql:latest
  image: yangjiandong/mysql:5.5
  volumes:
    - ./db:/var/lib/mysql
  environment:
    #- MYSQL_DATABASE=django
    #- MYSQL_ROOT_PASSWORD=mysql
    - DB_NAME=django
      #- DB_REMOTE_ROOT_NAME=root
      #- DB_REMOTE_ROOT_PASS=123
  ports:
    - "3306:3306"

redis:
  image: daocloud.io/redis:latest
  ports:
    - "6379:6379"
  volumes:
    - ./redisdata:/data

