version: '2.1'

services:

  db:
    image: one/mysql:5.7
    volumes:
      - ./mysql/mysql:/var/lib/mysql:rw
      - ./mysql/conf:/etc/mysql:ro
    privileged: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=mindoc
      - MYSQL_USER=root

